### ISSUE TITLE
Visualize plugin activity inside throughput/latency graphs

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#440]
**Is your feature request related to a problem? Please describe:**  
While we see the throughput and latency going up and down, we have to manually draw connections to plugin activity. 

**Please describe the solution you'd like:**  
Visualize keypoints of the plugin activity inside the throughput and latency graph to make plugin impact more visible.

**Affected Component(s):**  
`Frontend`

as requested by @Bensk1

**Comment by Bensk1** [comment]
This also includes introducing tags or log levels for log messages in Hyrise. Otherwise we cannot differentiate between not important messages like "Running... nothing to do here." and "Changed the whole system configuration."

**Comment by Bouncner** [comment]
Nothing final, but I'll start with a idea. We'll use tags in all the log messages that plugins are logging. You'll use these log message to filter relevant from irrelevant log messages.

Example: `[Status] Compression Plugin started` or `[Info] Segment 6 of 17 with LZ4…`.
We'll then agree then to only include status messages in the graphs.

What I am not sure about so far is how we "mark" the messages per plugin, so that we can put differently coloured markers into the graphs.

Opinions?
