### ISSUE TITLE
same colors for databases with similar IDs

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#556]
**Please describe the bug:**  
When you add a database with an ID that is only in the last number different from other database IDs, you often get the same database colors

**Please describe steps to reproduce:**  
1. Add a database with an ID like "hyrise-1"
2. Repeat with similar names ("hyrise-2", ...)
3. See bug

**What is the expected behavior? Please describe:**  
The colors should vary.

**Screenshot(s):**  
<img width="1263" alt="Screenshot 2020-04-23 at 14 47 36" src="https://user-images.githubusercontent.com/49514526/80101986-70980b80-8572-11ea-87b2-e7e9bbde5887.png">
<img width="1261" alt="Screenshot 2020-04-23 at 14 49 16" src="https://user-images.githubusercontent.com/49514526/80101989-71c93880-8572-11ea-8ca4-784545a4e204.png">
<img width="1260" alt="Screenshot 2020-04-23 at 14 50 22" src="https://user-images.githubusercontent.com/49514526/80101991-7261cf00-8572-11ea-8a45-bf9d5111e720.png">

**Affected Component(s):**  
`Frontend`

**Comment by Bouncner** [comment]
Before anybody tackles this issue on his own, let's discuss possible ways to approach it. Because I doubt it's super easy.

What I would like to see is the following:
* a database ID ideally has always the same colour
* colours don't repeat for acceptable numbers of databases (let's not discuss cases with more than 8 databases)
* as there will be cases where two database IDs would have the same colour, we need some way to **deterministically** find a suitable colour scheme for that 
* the order of added databases should not matter, I am fine with having changing colours when somebody later adds a new database (I don't think we can cover all situations)

**Comment by cH3n7i** [comment]
Maybe some kind of text to hex (or similar) could be a starting point here.
This would already grant 
• unique colors, since the ID has to be unique
• it's deterministic
• the order doesn't matter

• (technically) not repeating colors - this depends on the specific implementation, there can also be colors very similar with little difference

**Comment by Bouncner** [comment]
You either map to random colors (probably a lot of ugly ones) or to a fixed “nice” set of colors. This set is much smaller and hence you’ll get collisions again. You won’t get around to find means to handle collisions.

**Comment by cH3n7i** [comment]
What about mapping the color to the order of the databases instead of database itself.
In the way that e.g. 1st (left most) DB will be blue, 2nd yellow, 3rd green...
This way we take a lot of complexity out of the topic and introduce a tiny bit of user customization.
I usually find myself adding databases in the same order, they would get the same colors.
On the other hand we can control the visual aspect - we can favor pleasing colors while giving the user a little way of deciding what database gets the prepared colors.

This way we could have a first implementation that fixes the bug with relatively little work.
The next iteration with mapping the database-id/name to a color via fancy methods could be a baklog topic.

WDYT @Bouncner ?

**Comment by Bouncner** [comment]
Sounds really good to me. @Bensk1 , @monasobh , @kathwill  ... what do you think?

**Comment by Bensk1** [comment]
Didn't know that colors are still an issue. Sounds good to me.

**Comment by kathwill** [comment]
That is basically what we had before. Then you wanted to have the same colors for the same database IDs. This will not be ensured now because we can not tell the user to add databases in the same order.

**Comment by Bouncner** [comment]
Do you really want to start the blame game? I doubt it.

As long as you don't have a better idea, we need to settle this issue somehow. And having accidentally the same colors as now is not acceptable.
I am happy to discuss other ideas, but I am not willing to wait for another three weeks. I would still love to have deterministic colors for a database ID.

**Comment by schTi** [comment]
Another option would be to store the database color as cookie. This would ensure equal database colors for a single client. But then we could also think about storing the database color in the backend.

**Comment by Bouncner** [comment]
Sounds good to me, but I doubt it's worth the effort. What do you think?

Udo's idea sounds like a straightforward solution to both the initial issue (something in the 400s) and #556. We should langsam mal aus die Puschen kommen.
