### ISSUE TITLE
Disable adding a database when a workload is running

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#586]
**Is your feature request related to a problem? Please describe:**  
Currently it is possible to add a database, start a workload and then add another database. So there will be one instance with a running workload and one that might not even have the right data loaded. It is then not possible to load or delete tables because a workload is running.

**Please describe the solution you'd like:**  
Adding a database should be disabled when a workload is running. A warning dialog should be shown that might even has the option to stop the workload and then add a database.

**Comment by Alexander-Dubrawski** [comment]
When #572 is in dev, you could just simply stop the worker while adding a database and then start them. Would this fix your problem?

**Comment by Alexander-Dubrawski** [comment]
@kathwill is this problem solved? Can we close this issue?

**Comment by kathwill** [comment]
> This should not be handled in the frontend because when you reload the page directly after adding a database the workload will not be stopped.

@Alexander-Dubrawski We don't want to handle this problem in the frontend, so the problem still exists

**Comment by PeterTsayun** [comment]
> The workload and the workers should be stopped, when a workload is running and a database is added.

I don't really see the use case of adding a database while a workload is being executed. How about rejecting the adding of the database in the backend, if the workers are running by already registered databases? It would simplify the logic and make the interaction with the `DatabaseManager` easier.

**Comment by Alexander-Dubrawski** [comment]
> > This should not be handled in the frontend because when you reload the page directly after adding a database the workload will not be stopped.
> 
> @Alexander-Dubrawski We don't want to handle this problem in the frontend, so the problem still exists

Can you please be more specific why you don't want to handle this in the frontend? What exactly are the reasons? 

In my opinion, it is always cleaner to handle the start/stop of the worker, workload, and add/delete of the database explicit (so the frontend tells the backend to add/delete the database,...). If we would handle this in the backend the behavior in this use case of the cockpit wouldn't be so obvious to the user. I would suggest handling this in the frontend. My suggestion would be the following: 

If we try to add a database while a workload is running, we could show a warning in the frontend to the user displaying that the worker at the new database are not running and that the workers need to be restarted (so stop and start a workload again). Or the frontend could tell the user that it is just not possible to add a database while a workload is in execution.
If it is a real use case to add databases in the execution of a workload we could add an endpoint that starts the workers explicitly on a database and loads data explicitly as well.  But this would be some more work to implement. 

@Bensk1 @Bouncner is it a use case to add a database while a workload is executed?

**Comment by cH3n7i** [comment]
In my opinion this case should be handled in Backend and Frontend.

Why in the Backend?
This is, where all/most of our logic and heavy lifting happens and as long as we open the API to everything (e.g. via SwaggerUI) we can't rely on other parts of catching a behavior that might happen due to the API and missing restrictions.

Why in the Frontend?
Simple answer: UX
If the user can click something, it will be clicked. Even if we can catch unwanted behavior silently in the Backend we should aim for a clear and easy Interface and UX. Otherwise it will just happen again.

My suggestion would be a 3-step implementation like so
1. Frontend: Discourage/disable adding new databases while workloads are running (very similar to @Alexander-Dubrawski idea)
> If we try to add a database while a workload is running, we could show a warning in the frontend to the user displaying that the worker at the new database are not running and that the workers need to be restarted (so stop and start a workload again). Or the frontend could tell the user that it is just not possible to add a database while a workload is in execution.

2. Backend: Adding a database while running the workload stops the workload
Frontend: Show a warning that adding a database will stop running workloads.
3. Backend: Added databases load the necessary data and join the workload.
Frontend: Show a warning, that there might be missing data due to the late join of the added database.

**Comment by PeterTsayun** [comment]
> * Backend: Adding a database while running the workload stops the workload
>   Frontend: Show a warning that adding a database will stop running workloads.
> * Backend: Added databases load the necessary data and join the workload.
>   Frontend: Show a warning, that there might be missing data due to the late join of the added database.

I think, if we would stop workload when adding a new database, the stopping of the workload will be a side effect, which, in my opinion, is semantically separated from the logic of adding a new database.

Instead of mixing the workload and database logic, I would suggest simply reject adding a new database while the workload is running in the backend, as it is not a use case anyway (we still can disable corresponding buttons in the frontend). I that way, we only need to make some minor changes and the returned data and behaviour of the backend remains consistent.

**Comment by Alexander-Dubrawski** [comment]
@PeterTsayun @cH3n7i  thanks for the nice suggestions, but we should ask the client in the next meeting what behavior they expect. Then we can find an optimal solution together.
