### ISSUE TITLE
Bug in component-communication

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/Cockpit#715]
**Please describe the bug:**  
There seems to be a problem in the communication between the docker containers. For example, the message from the backend container doesn't reach the generator container. 

**Please describe steps to reproduce:**  
1. build container and images via `docker-compose up -d --build`
2. Access swagger `http://0.0.0.0:8000/` 
3. try to get all workloads (get) `/workload/`
4. The backend is not receiving a response  

**What is the expected behavior? Please describe:**  
The backend should get a response

**Affected Component(s):**  
`docker set up`

**Additional context:**  
We accessed the containers via a subshell and check if the ports are mapped correctly. This is the case.

**Comment by cH3n7i** [comment]
Pinging from within the Backend Container to the Generator Container by using its service name as hostname (see docker-compose.yml).
```
docker exec cockpit_backend_1 ping -c 3 generator                                                                                        
PING generator (172.18.0.6) 56(84) bytes of data.
64 bytes from cockpit_generator_1.cockpit_default (172.18.0.6): icmp_seq=1 ttl=64 time=0.101 ms
64 bytes from cockpit_generator_1.cockpit_default (172.18.0.6): icmp_seq=2 ttl=64 time=0.048 ms
64 bytes from cockpit_generator_1.cockpit_default (172.18.0.6): icmp_seq=3 ttl=64 time=0.064 ms

--- generator ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 79ms
```

The Container resolve and communicate with each other just fine.

**Comment by Alexander-Dubrawski** [comment]
I'm not sure if the problem lies in the backend. The backend is working just if you start the components without the docker setup. If you start the components and then do:

1. Access swagger `http://0.0.0.0:8000/` 
2. try to get all workloads (get) `/workload/`

There is no failure.

**Comment by cH3n7i** [comment]
> **Please describe the bug:**
> There seems to be a problem in the communication between the ~~docker containers~~ _Cockpit components._ For example, the message from the backend ~~container~~ _component_ doesn't reach the generator ~~container~~ _component_.
> 
> **Please describe steps to reproduce:**
> 
>     1. build container and images via `docker-compose up -d --build`
> 
>     2. Access swagger `http://0.0.0.0:8000/`
> 
>     3. try to get all workloads (get) `/workload/`
> 
>     4. The backend is not receiving a response
> 
> 
> **What is the expected behavior? Please describe:**
> The backend should get a response
> 
> **Affected Component(s):**
> ~~`docker set up`~~ _Backend_
> 
> **Additional context:**
> We accessed the containers via a subshell and check if the ports are mapped correctly. This is the case.

Please note, with the usage of `docker-compose up -d --build` you're building a new image based on your local repo. Using `docker-compose -f docker-compose.deployment.yml up -d` will create the setup based on the current dev-repo

**Comment by Alexander-Dubrawski** [comment]
> > **Please describe the bug:**
> > There seems to be a problem in the communication between the ~docker containers~ _Cockpit components._ For example, the message from the backend ~container~ _component_ doesn't reach the generator ~container~ _component_.
> > **Please describe steps to reproduce:**
> > ```
> > 1. build container and images via `docker-compose up -d --build`
> > 
> > 2. Access swagger `http://0.0.0.0:8000/`
> > 
> > 3. try to get all workloads (get) `/workload/`
> > 
> > 4. The backend is not receiving a response
> > ```
> > 
> > 
> > **What is the expected behavior? Please describe:**
> > The backend should get a response
> > **Affected Component(s):**
> > ~`docker set up`~ _Backend_
> > **Additional context:**
> > We accessed the containers via a subshell and check if the ports are mapped correctly. This is the case.
> 
> Please note, with the usage of `docker-compose up -d --build` you're building a new image based on your local repo. Using `docker-compose -f docker-compose.deployment.yml up -d` will create the setup based on the current dev-repo

But my local repro is working just fine. And I tested it with the newest version of the dev branch. My point is just that I really don't think that the problem lies at the site of the backend.

**Comment by Alexander-Dubrawski** [comment]
@cH3n7i It's kind of a longshot but you can try to remove the aliases from the `.env.example` and `settings.py` and replace them by `localhost` or `0.0.0.0`. I hade some problems with the aliases (especially in docker) in the past. 
Another look worth into is https://github.com/NumesSanguis/pyzmq-docker

**Comment by cH3n7i** [comment]
> @cH3n7i It's kind of a longshot but you can try to remove the aliases from the `.env.example` and `settings.py` and replace them by `localhost` or `0.0.0.0`. I hade some problems with the aliases (especially in docker) in the past.
> Another look worth into is https://github.com/NumesSanguis/pyzmq-docker

The aliases (service names) where introduced to enable inter container communication, since you don't want to rely on ever-changing IPs with containers. 

From https://github.com/NumesSanguis/pyzmq-docker 2. Docker-Docker with docker-compose - Notes:
> It connects the pub micro-service to the sub micro-service with tcp://sub:5550. Docker automatically turns sub into the IP of the subscriber micro-service.

And if you look into https://github.com/NumesSanguis/pyzmq-docker/blob/master/docker-compose.yml 
`["python", "main.py", "--ip", "sub"]` They are running it with the service name/hostname since Docker Compose is able to substitute it.

Assuming you meant `localhost` and `127.0.0.1` as one way and `0.0.0.0` as a different.
While `localhost` and `127.0.0.1` will not loop outside of a container, vm or machine, `0.0.0.0` is another story.  
Using `localhost` or `0.0.0.0` are not the same - e.g. defining the listening part of components would result in the service just listening to itself vs listening to everything. Using `localhost` or `0.0.0.0` as target will yield different results respectively.

This creates the following;
Your host will hand down ports the way it is defined within the`docker-compose(.deployment).yml`. 
The backend service maps `8000` to `8000`; the frontend is mapped from `80` to `5000`
You will be able to access SwaggerUI via `http://localhost:8000` on your host or the cockpit-backend but not from any other container.
You will be able to access the Frontend via `http://localhost:80` (or simply `http://localhost` as Port 80 is the http default) on your host and with `localhost:5000` from within the frontend container.

You will be able to ping `backend` from any cockpit-container that was created with docker-compose next to the `backend` container.
You will not be able to ping `backend` from your host, as it should not be able to recognise it from the network your host resides.

For more information see https://docs.docker.com/compose/networking/

**Comment by Alexander-Dubrawski** [comment]
I did some more debugging. I deleted every container on my Mac with `docker system prune -a --volumes` and the problem in the backend seams to be resolved. But I am still not able to add a database in the frontend and I wasn't able to find a solution.

**Comment by Alexander-Dubrawski** [comment]
I opened a new Issue  #716 for the bug that we can not add a database in the frontend. This error occurs in the docker set up and in the setup without docker.
